name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OCTOPUS_PROJECT_NAME: OctoService
  OCTOPUS_SPACE_NAME: Default
  OCTOPUS_ENVIRONMENT_NAME: dev
  key:  
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set version
        run: echo "::set-env name=PACKAGE_VERSION::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          
      - name: Make package directories
        run: mkdir -p ./packagesoutput/
          
      - name: Build
        run: dotnet publish -c Release -r linux-x64 --self-contained false --output ./packagesoutput/OctoService
        
      - name: Install Octopus CLI
        run: |
          sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https && \
          curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - && \
          sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" && \
          sudo apt update && sudo apt install octopuscli
          
      - name: Package and push to Octopus
        run: |
          octo pack --id="OctoService" --format="Zip" --version="$PACKAGE_VERSION" --basePath="./packagesoutput/OctoService" --outFolder="./packages"
          octo push --package="./packages/OctoService.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}"
          
      - name: Create and deploy release
        run: octo create-release --project="$OCTOPUS_PROJECT_NAME" --packageVersion="$PACKAGE_VERSION" --releaseNumber="$PACKAGE_VERSION" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}" --space="$OCTOPUS_SPACE_NAME" --deployTo="$OCTOPUS_ENVIRONMENT_NAME"
        
